### PR TITLE
Update: change request

### PR DESCRIPTION
**Pull request by Gittestythingy**
Change CSS to red

### CODE REVIEW

**Comment by Gittestythingy** [comment]
hey, is this ok if we change it to red? Cheers

**Comment by 5c13nc3Guy** [comment]
Yep, go ahead. Cheers

**Comment by 5c13nc3Guy** [comment]
@Gittestythingy please change line (54) as not recognised CSS for color change edit.

**Comment by 5c13nc3Guy** [comment]
test commeney

**Pull request closed without merging**
